# Generated by Django 6.1 on 2026-08-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم اللعبة')),
                ('category', models.CharField(max_length=50, verbose_name='التصنيف')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='Player', max_length=50, verbose_name='اسم اللاعب')),
                ('game_name', models.CharField(max_length=100, verbose_name='اللعبة')),
                ('result', models.CharField(max_length=100, verbose_name='النتيجة')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت اللعب')),
            ],
        ),
    ]
